services:
  backend:
    image: fizcko/sms-gateway
    restart: always
    ports:
      - 5000:5000
    devices:
      - "/dev/ttyUSB2:/dev/ttyUSB2"
    depends_on:
      - "db"
    environment:
      GAMMU_DEVICE: /dev/ttyUSB2
      MYSQL_HOST: db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 88qpRR87pa78fff
      MYSQL_DATABASE: smsd
  db:
    image: mariadb
    restart: always
    volumes:
      - /opt/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 88qpRR87pa78fff
      MYSQL_DATABASE: smsd
